---
title: "Courses/Workshops"
output: 
  html_document:
    theme: cosmo
---

## Teaching Demo

**[Live code file](https://docs.google.com/document/d/11tTeVhv5v9YjRu8SGHGvJRPy0bo1OyuSpZq-Hl-P-UY/edit?usp=sharing)**

 **[TeachingDemoKNN.R](documents/TeachingDemoKNN.R)**

 **[oxford_houses.csv](documents/data/oxford_houses.csv)**

## Web Resources For Data Viz and Stat Learning Students

 **[R for Data Science -- Free e-Book](https://r4ds.had.co.nz/)**
 
 **[Advanced R -- Free e-book](http://adv-r.had.co.nz/)**

 **[An Introduction to Statistical Learning -- Author Website with book pdf ](http://faculty.marshall.usc.edu/gareth-james/ISL/)**

## Red Carpet - Bridges 

 **[RedCarpetDay-Bridges-Talk-TitanicHandout.pdf](documents/RedCarpetDay-Bridges-Talk-TitanicHandout.pdf)**

 **[Data-visualization-exploration.R](documents/Data-visualization-exploration.R)**

 **[Data-visualization-exploration.txt](documents/Data-visualization-exploration.txt)**

## Data Science Night Slides and Code

 **[DataScienceNights_blank.R](documents/DataScienceNights_blank.R)**

 **[DataScienceNights.R](documents/DataScienceNights.R)**

 **[December2017FlightDelays.csv](documents/data/December2017FlightDelays.csv)**
 
 **[December2017Weather.RData](documents/data/December2017Weather.RData)**
 
 **[WeatherStationsUSA.csv](documents/data/WeatherStationsUSA.csv)**
 
 **[DataWrangling.html](documents/DataWrangling.html)**

 **[ggplot2Intro.pdf](documents/ggplot2Intro.pdf)**

 **[ggplot2Intro.R](documents/ggplot2Intro.R)**
 
## Quick Access Datasets for Classes

 **[Airfares.csv](documents/data/Airfares.csv)**

 **[baseball.csv](documents/data/baseball.csv)**
 
 **[batting.Rdata](documents/data/batting.Rdata)**

 **[DelaysDec2014.Rdata](documents/data/DelaysDec2014.Rdata)**

 **[nasadata.csv](documents/data/nasadata.csv)**

 **[nycCabsSample2014Dec.Rdata](documents/data/nycCabsSample2014Dec.Rdata)**

 **[ohioBRFSS2016.csv](documents/data/ohioBRFSS2016.csv)**

 **[OhioWeatherStations2013.csv](documents/data/OhioWeatherStations2013.csv)**
 
 **[pitching_careers.csv](documents/data/pitching_careers.csv)**

 **[pitchingSample.csv](documents/data/pitchingSample.csv)**

 **[Pitching2014.csv](documents/data/Pitching2014.csv)**

 **[realestate.csv](documents/data/realestate.csv)**

 **[shuffled_playlist.csv](documents/shuffled_playlist.csv)**

 **[SLahman_Batting2016.csv](documents/SLahman_Batting2016.csv)**

 **[StateCountyFIPS.csv](documents/data/StateCountyFIPS.csv)**

 **[StateStatsBRFSS.csv](documents/data/StateStatsBRFSS.csv)**

 **[StateStatsBRFSSMessy.csv](documents/data/StateStatsBRFSSMessy.csv)**