---
title: "CV"
output: 
  html_document:
    theme: cosmo
---


* **[Curriculum Vitae](documents/KarstenMaurerCV.pdf)**
<!-- * **[Teaching Philosophy](documents/KarstenMaurerTeachPhil.pdf)** -->
<!-- * **[Research Statement](documents/KarstenMaurerResearchStatement.pdf)** -->

## Publications

*  *[Content Audit for P-value Principles in Introductory Statistics](https://www.tandfonline.com/doi/full/10.1080/00031305.2018.1537890)* (Maurer K. Hudiburgh L., Werwinski L., Bailer A.J., 2019)
*  *[A tale of four cities: exploring the soul of State College,Detroit, Milledgeville and Biloxi](https://link.springer.com/epdf/10.1007/s00180-018-00863-x?author_access_token=N0GW9Uj-8Jrt72Lb3em0D_e4RwlQNchNByi7wbcMAY7uBPRsrLmeTb896xXQHbgLPTBcIH24Z2vemKbresc_EdEmV7S09WEUrW030Eibbhc48JfQO2VYCbgu5VVF0U86DplAw0GM19N00Ma7cM3ojw%3D%3D)* (Maurer K. Osthus D., Loy A., 2019)
*  *[The Impact of Video Proctoring in Online Courses](https://eric.ed.gov/?id=EJ1195526)* (Alessio H., Maurer K., 2018)
*  *[ggvoronoi: Voronoi Diagrams and Heatmaps with ggplot2](https://www.theoj.org/joss-papers/joss.01096/10.21105.joss.01096.pdf)* (Garrett R., Nar A., Fisher T., Maurer K., 2018)
*  *[Interaction of Proctoring and Student Major on Online Test Performance](http://www.irrodl.org/index.php/irrodl/article/view/3698/4843)* (Alessio H., Malay N., Maurer K., Bailer J., Rubin B., 2018)
*  *[Examining the Impact on Mortality Arising from Climate Change: Important Findings for the Insurance Industry](https://link.springer.com/article/10.1007/s13385-018-0178-2)* (Miljkovic T., Miljkovic D., Maurer K., 2018)
*  *[Comparison of Learning Outcomes for Randomization-Based and Traditional Inference Curricula in a Designed Educational Experiment](https://olj.onlinelearningconsortium.org/index.php/olj/article/view/885)* (Alessio, Malay, Maurer, Bailer, Rubin, 2017)
*  *[Examining the Effect of Proctoring on Online Test Scores](http://escholarship.org/uc/item/0wm523b0)* (Maurer, Lock, 2016)
*  *[Self-selection and variations in the laboratory measurement of other-regarding preferences across subject pools: evidence from one college student and two adultsamples](https://link.springer.com/article/10.1007/s10683-012-9327-7)* (Anderson, Burks, Carpenter, Goette, Maurer, Nosenzo, Potter, Rocha, Rustichini, 2013)


## Submitted Manuscripts

*  *[Facility Locations Utility for Uncovering Classifier Overconfidence](documents/papers/MaurerBennetteAAAI.pdf)*
(Maurer, Bennette, 2019)
*  *Iterative Quantile Nearest Neighbors*
(Maurer, 2019)
*  *What Do Students Gain from Games? Dice Games vs. Word Problems*
(Maurer, Hudiburgh, Werwinski, 2019)
*  *A shiny Opportunity to Interact with Large Databases in Introductory Statistics*
(Maurer, Hofmann, 2019)
*  *Harnessing Adversarial Distances Uncovering Classifier Overconfidence*
(Bennette, Maurer, 2019)

## Presentations
*  JSM 2018 - **Iterative Quantile Nearest Neighbors**
*  JSM 2017 - **[Bin-Weighted Ensemble Classifiers](documents/conferences/JSM2017.pdf)**
*  JSM 2016 - **[Traditional vs. Simulation-Based: Curricula Comparison in a Small Scale Educational Experiment](documents/conferences/JSM2016.pdf)** 
*  JSM 2014 - **[Comparison of Learning Outcomes from Traditional and Randomization-Based Inference Curricula in a Designed Experiment](documents/conferences/JSM2014.pdf)**
*  ICOTS 2014 - **[A Shiny New Opportunity for Big Data in Statistics Education](documents/conferences/ICOTS2014.pdf)**
*  JSM 2013 - **[A Tale of Four Cities: Exploring the Soul of Biloxi, Detroit, Milledgeville, and State College](documents/conferences/JSM2013.pdf)**
*  JSM 2011 - **[Using R to Constuct a Graphical User Interface for an Interactive Fitness Log](documents/conferences/JSM2011.pdf)**


## Works in Progress Toward Publication

*  *[Student Project] Lady Tasting Tea Lineup Plots for Visual Inference*
*  *[Student Project] Embedding Initalization for Image Classification in an Active Learning Framework*
*  *[Student Project] Applications of Voronoi Tesselations*
*  *[Student Project] Evaluating Instructor vs Publisher Created Homework Sets*
*  *[Statistical Consulting] Beaver Dam Meta-Analysis*
*  *[Statistical Consulting] Baby Food Evaluation of IDDSI Standards*
*  *[Statistical Consulting] Eye-Tracking Analysis of Webpage Designs*
*  *Bin-Weighted Stacked Ensemble Classifiers*


